version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:prod"]
    expose:
      - '8000'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - backend
