enum MimeType {
  APPLICATION_DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  APPLICATION_PDF = 'application/pdf',
  MULTIPART_FORM_DATA = 'multipart/form-data',
  TEXT_HTML = 'text/html',
  VIDEO_AVI = 'video/avi',
  VIDEO_MKV = 'video/mkv',
  VIDEO_MP4 = 'video/mp4',
  VIDEO_MOV = 'video/mov',
  VIDEO_WEBM = 'video/webm',
  VIDEO_MPG = 'video/mpeg',
  VIDEO_3GP = 'video/3gpp',
  VIDEO_3G2 = 'video/3gpp2',
  VIDEO_ASF = 'video/x-ms-asf',
  VIDEO_FLV = 'video/x-flv',
  VIDEO_M4V = 'video/x-m4v',
  VIDEO_MTS = 'video/mts',
  VIDEO_OGG = 'video/ogg',
  VIDEO_TS = 'video/mp2t',
  VIDEO_VOB = 'video/x-ms-vob',
  VIDEO_WMV = 'video/x-ms-wmv',
  VIDEO_DIVX = 'video/divx',
  VIDEO_F4V = 'video/x-f4v',
  VIDEO_M2TS = 'video/m2ts',
  VIDEO_QT = 'video/quicktime',
  VIDEO_WEBM_VP8 = 'video/webm; codecs="vp8"',
  VIDEO_WEBM_VP9 = 'video/webm; codecs="vp9"',
  APPLICATION_M3U8 = 'application/vnd.apple.mpegurl',
}

export { MimeType };
